
import './styles/globals.scss'
import { Roboto, Spline_Sans } from 'next/font/google'


const roboto = Roboto({ weight: '700', preload: false })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
